name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  azure_webApp_name: Trilathon
  azure_webApp_packagePath: "./publish"
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./back/Back.sln

      - name: Build
        run: dotnet build ./back/Back.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./back/Back.sln --configuration Release --no-build --output "${{env.azure_webApp_packagePath}}"

      - name: Deployment
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{env.azure_webApp_name}}
          package: "${{env.azure_webApp_packagePath}}"
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
